/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AvatarService } from "../avatar.service";
import { AvatarCreateInput } from "./AvatarCreateInput";
import { Avatar } from "./Avatar";
import { AvatarFindManyArgs } from "./AvatarFindManyArgs";
import { AvatarWhereUniqueInput } from "./AvatarWhereUniqueInput";
import { AvatarUpdateInput } from "./AvatarUpdateInput";
import { ImageFindManyArgs } from "../../image/base/ImageFindManyArgs";
import { Image } from "../../image/base/Image";
import { ImageWhereUniqueInput } from "../../image/base/ImageWhereUniqueInput";

export class AvatarControllerBase {
  constructor(protected readonly service: AvatarService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Avatar })
  async createAvatar(@common.Body() data: AvatarCreateInput): Promise<Avatar> {
    return await this.service.createAvatar({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
        image: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Avatar] })
  @ApiNestedQuery(AvatarFindManyArgs)
  async avatars(@common.Req() request: Request): Promise<Avatar[]> {
    const args = plainToClass(AvatarFindManyArgs, request.query);
    return this.service.avatars({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
        image: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Avatar })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async avatar(
    @common.Param() params: AvatarWhereUniqueInput
  ): Promise<Avatar | null> {
    const result = await this.service.avatar({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
        image: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Avatar })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAvatar(
    @common.Param() params: AvatarWhereUniqueInput,
    @common.Body() data: AvatarUpdateInput
  ): Promise<Avatar | null> {
    try {
      return await this.service.updateAvatar({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          description: true,
          image: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Avatar })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAvatar(
    @common.Param() params: AvatarWhereUniqueInput
  ): Promise<Avatar | null> {
    try {
      return await this.service.deleteAvatar({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          description: true,
          image: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/images")
  @ApiNestedQuery(ImageFindManyArgs)
  async findImages(
    @common.Req() request: Request,
    @common.Param() params: AvatarWhereUniqueInput
  ): Promise<Image[]> {
    const query = plainToClass(ImageFindManyArgs, request.query);
    const results = await this.service.findImages(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        prompt: true,
        generatedImage: true,

        project: {
          select: {
            id: true,
          },
        },

        avatar: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/images")
  async connectImages(
    @common.Param() params: AvatarWhereUniqueInput,
    @common.Body() body: ImageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      images: {
        connect: body,
      },
    };
    await this.service.updateAvatar({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/images")
  async updateImages(
    @common.Param() params: AvatarWhereUniqueInput,
    @common.Body() body: ImageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      images: {
        set: body,
      },
    };
    await this.service.updateAvatar({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/images")
  async disconnectImages(
    @common.Param() params: AvatarWhereUniqueInput,
    @common.Body() body: ImageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      images: {
        disconnect: body,
      },
    };
    await this.service.updateAvatar({
      where: params,
      data,
      select: { id: true },
    });
  }
}
